AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  LF1v2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: LF1_V2.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 300
      Role: 'arn:aws:iam::690128978051:role/service-role/LF1-role-go4oal0b'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: uploadedJPG
      Layers:
        - 'arn:aws:lambda:us-east-1:690128978051:layer:libs:4'
  Bucket1:
    Type: 'AWS::S3::Bucket'
